### ISSUE TITLE
Missing Features

### ISSUE THREAD

**Issue by trmcnvn** [trmcnvn/DigitalOcean.API#45]
- [x] Block Storage (#46)
- [x] Block Storage Actions (#47)
- [x] Databases (#50)
- [x] Droplets (#51)
  - [x] Create multiple Droplets
  - [x] List Neighbors for a Droplet
  - [x] List all Droplet Neighbors
- [x] Droplet Actions (#51)
  - [x] Enable Backups
  - [x] Acting on Tagged Droplets
- [x] Floating IPs (#48)
- [x] Floating IP Actions (#48)
- [x] Firewalls (#49)
- [x] Images (#51)
  - [x] Create Image (#43)
  - [x] List Images by Tag
  - [x] List all actions for an Image
- [x] Image Actions
  - [x] Convert an Image to a Snapshot
- [x] Kubernetes (#52)

**Comment by Nicholi** [comment]
> * [ ]  Droplets
>   
>   * [ ]  Create multiple Droplets
>   * [ ]  List Neighbors for a Droplet
>   * [ ]  List all Droplet Neighbors
> * [ ]  Droplet Actions
>   
>   * [ ]  Enable Backups
>   * [ ]  Acting on Tagged Droplets
> * [ ]  Images
>   
>   * [ ]  List Images by Tag
>   * [ ]  List all actions for an Image
> * [ ]  Image Actions
>   
>   * [ ]  Convert an Image to a Snapshot

My next PR I planned to handle these ones. And a few other new/missing properties, here is my current working branch: https://github.com/Nicholi/DigitalOcean.API/tree/new_or_missing

**Comment by Nicholi** [comment]
https://github.com/trmcnvn/DigitalOcean.API/pull/51 should cover everything except Kubernetes.
